services:
  web:
    build:
      context: .
      dockerfile: docker/prod/web/Dockerfile
    command: gunicorn src.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8009:8000"
    env_file:
      - docker/prod/env/.prod.env
    depends_on:
      - db
    volumes:
      - ./web/:/home/app/web
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - docker/prod/env/.db.prod.env

volumes:
  postgres_data: